[theme]
base = "light"
primaryColor = "#e60012"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f7f7"
textColor = "#111111"
font = "sans-serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
